### ISSUE TITLE
Offset Position Issue

### ISSUE THREAD

**Issue by nintenjo** [betavr/steamvr_driver_hydra#17]
Not sure if this is an issue with the tracking, my room setup or SteamVR.. 

But when i run any SteamVR app and hold the controllers next to me head and calibrate them, as i move my hands away from my body, they always drift to the right by about (6-10" .. thats a rough virtual measurement). It means i constantly have to hold my hands to the left a little to compensate?

The amount it drifts to the side gets worse the further they are from the calibrated position.

**Comment by betavr** [comment]
Yeah, drift is considered normal unfortunately. Every hydra has its own manufacturing problems, because the little "receiver" coils inside the controllers are not perfectly aligned usually. Also magnetic fields near your computer have a very large impact on the hydra. I'd try moving around the base station first to see if it gets better depending on the location.
