### ISSUE TITLE
Steam VR not detecting it at all

### ISSUE THREAD

**Issue by harryjt** [betavr/steamvr_driver_hydra#6]
Steam VR isn't detecting my hydras, whatever I do it wont work

**Comment by TechnoHunter** [comment]
Have you tried copying the drivers in both Steam\Config and %ProgramFiles(x86)%\Steam\steamapps\common\SteamVR\drivers%? Also making sure to have the steamvr.vrsettings in the steamvr folder as well?

**Comment by betavr** [comment]
Check the contents of vrserver.txt for related errormessages in the Steam\logs directory.

Btw what is the path to your SteamVR install folder?

**Comment by djdevin** [comment]
same here, but to answer the question instead of "SteamVR" mine has a path of "OpenVR", so the installer scripts won't work

**Comment by harryjt** [comment]
For some reason I don't have a vrserver.txt https://gyazo.com/0dd3cf825f146a3c09203d466f573c33 and the path for my steam VR is on my C: drive

**Comment by betavr** [comment]
@harryjt Please include the output of vrpathreg.exe (probably found in "c:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win32" folder).

@djdevin I assume that install path was used in the past. Have you tried reinstalling SteamVR?

**Comment by djdevin** [comment]
@betavr actually I installed very recently. have you tried reinstalling SteamVR? :)

For now I copied the driver folder into drivers instead of using vrpathreg, and confirmed the hydras were working in the compositor!

**Comment by betavr** [comment]
@djdevin Alright, I'm going to modify the install script then. Can you post your full steamvr install path please?

**Comment by crtro** [comment]
My vrpathreg.exe gives:

"C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win64\vrpathreg.exe"
Runtime path = C:\Program Files (x86)\Steam\steamapps\common\SteamVR\
Config path = G:\steam\config
Log path = G:\steam\logs
External Drivers:
        C:\Program Files (x86)\SteamVR Hydra driver\hydra"

No idea why the config/log path is in G:. I even reinstalled steam and didn't add G: as a folder and it's the same output, perhaps it didn't delete the registry files upon deletion?

**Comment by cbuchner1** [comment]
You might want to check out the config_tool I added to my Leap Motion driver repository. It uses a C++ program and RapidJSON to configure the driver path and to amend the streamvr.vrconfig file with driver specific information. This means previous user settings are fully retained, yay.

The .msi installer had to be changed to target 64 bit machines and the config_tool.exe had to be included as a 64 bit version, otherwise I think it ended up reading registry entries from the WOW6432 registry node (which would _not_ contain information about the StreamVR installation folder).

I think this new method of installation is more reliable with respect to differing locations of Steam and StreamVR paths.

**Comment by betavr** [comment]
Thanks, will check it out!

**Comment by betavr** [comment]
The driver is going to be downloadable from Steam soon, so I'm closing this.
